version: '3.1'
services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes: 
      - ./data:/var/lib/mysql
      - ./backup:/tmp/backup/mysql
    ports:
      - 3306:3306
