CREATE TABLE IF NOT EXISTS `AuthorizationCode` (
    `CodeId` VARCHAR(100) NOT NULL
  , `ApplicationId` CHAR(36) NOT NULL
  , `AccountId` CHAR(36) NOT NULL
  , `Status` VARCHAR(20) NOT NULL
  , `ExpiryTime` DATETIME NOT NULL
  , `CreateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , `UpdateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY (`CodeId`)
);
