CREATE TABLE IF NOT EXISTS `AuthorizationCode` (
    `Code` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
  , `ApplicationId` CHAR(36) NOT NULL
  , `AccountId` CHAR(36) NOT NULL
  , `Status` VARCHAR(20) NOT NULL
  , `ExpiryTime` DATETIME NOT NULL
  , `CreateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , `UpdateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , `ConcurrencyToken` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY (`Code`)
);
