CREATE TABLE IF NOT EXISTS `DataProtection` (
    `DataProtectionId` VARCHAR(256) NOT NULL
  , `Element` TEXT NOT NULL
  , `CreateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , `UpdateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY (`DataProtectionId`)
);