CREATE TABLE IF NOT EXISTS `AccessToken` (
    `TokenId` VARCHAR(100) NOT NULL
  , `Name` VARCHAR(100) NOT NULL
  , `Description` VARCHAR(400) NOT NULL
  , `ApplicationId` CHAR(36) NOT NULL
  , `PrincipalType` VARCHAR(20) NOT NULL
  , `PrincipalId` CHAR(36) NULL
  , `Scopes` TEXT NOT NULL
  , `Status` VARCHAR(20) NOT NULL
  , `ExpiryTime` DATETIME NOT NULL
  , `CreateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , `UpdateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY (`TokenId`)
);