//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.Boilerplate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.Boilerplate.Web.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は英数字とハイフンのみで入力してください。.
        /// </summary>
        public static string DataAnnotationDataCode {
            get {
                return ResourceManager.GetString("DataAnnotationDataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は数字2、4、6、8文字のいずれかで入力してください。.
        /// </summary>
        public static string DataAnnotationDataTree {
            get {
                return ResourceManager.GetString("DataAnnotationDataTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は重複登録できません。.
        /// </summary>
        public static string DataAnnotationDuplicatedStringArray {
            get {
                return ResourceManager.GetString("DataAnnotationDuplicatedStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationEnumContains {
            get {
                return ResourceManager.GetString("DataAnnotationEnumContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationEnumDataType {
            get {
                return ResourceManager.GetString("DataAnnotationEnumDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationGuid {
            get {
                return ResourceManager.GetString("DataAnnotationGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値は日付と時刻の形式で入力してください。.
        /// </summary>
        public static string DataAnnotationISO8601 {
            get {
                return ResourceManager.GetString("DataAnnotationISO8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値は日付の形式で入力してください。.
        /// </summary>
        public static string DataAnnotationISO8601Date {
            get {
                return ResourceManager.GetString("DataAnnotationISO8601Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}個以内で入力してください。.
        /// </summary>
        public static string DataAnnotationMaxLength {
            get {
                return ResourceManager.GetString("DataAnnotationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}以上{2}以下で入力してください。.
        /// </summary>
        public static string DataAnnotationRange {
            get {
                return ResourceManager.GetString("DataAnnotationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;を入力してください。.
        /// </summary>
        public static string DataAnnotationRequired {
            get {
                return ResourceManager.GetString("DataAnnotationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は空の要素を登録できません。.
        /// </summary>
        public static string DataAnnotationRequiredStringArray {
            get {
                return ResourceManager.GetString("DataAnnotationRequiredStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に指定可能な項目リストを確認してください。.
        /// </summary>
        public static string DataAnnotationSort {
            get {
                return ResourceManager.GetString("DataAnnotationSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}文字以内で入力してください。.
        /// </summary>
        public static string DataAnnotationStringLength {
            get {
                return ResourceManager.GetString("DataAnnotationStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の要素は{1}文字以内で入力してください。.
        /// </summary>
        public static string DataAnnotationStringLengthArray {
            get {
                return ResourceManager.GetString("DataAnnotationStringLengthArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同時実行トークン.
        /// </summary>
        public static string DisplayCommonConcurrencyToken {
            get {
                return ResourceManager.GetString("DisplayCommonConcurrencyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限種別.
        /// </summary>
        public static string DisplayCommonGrantType {
            get {
                return ResourceManager.GetString("DisplayCommonGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページ番号.
        /// </summary>
        public static string DisplayCommonPage {
            get {
                return ResourceManager.GetString("DisplayCommonPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページサイズ.
        /// </summary>
        public static string DisplayCommonPageSize {
            get {
                return ResourceManager.GetString("DisplayCommonPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索キーワード.
        /// </summary>
        public static string DisplayCommonQuery {
            get {
                return ResourceManager.GetString("DisplayCommonQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並び順.
        /// </summary>
        public static string DisplayCommonSort {
            get {
                return ResourceManager.GetString("DisplayCommonSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 都市コード.
        /// </summary>
        public static string DisplayForecastCityCode {
            get {
                return ResourceManager.GetString("DisplayForecastCityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国コード.
        /// </summary>
        public static string DisplayForecastCountryCode {
            get {
                return ResourceManager.GetString("DisplayForecastCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付.
        /// </summary>
        public static string DisplayForecastDate {
            get {
                return ResourceManager.GetString("DisplayForecastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予報コード.
        /// </summary>
        public static string DisplayForecastForecastCode {
            get {
                return ResourceManager.GetString("DisplayForecastForecastCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天気.
        /// </summary>
        public static string DisplayForecastSummary {
            get {
                return ResourceManager.GetString("DisplayForecastSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 気温.
        /// </summary>
        public static string DisplayForecastTemperature {
            get {
                return ResourceManager.GetString("DisplayForecastTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証トークンの有効期限が切れています。.
        /// </summary>
        public static string ErrorResultAuthorizationTokenExpired {
            get {
                return ResourceManager.GetString("ErrorResultAuthorizationTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要求が正しくありません。.
        /// </summary>
        public static string ErrorResultBadRequest {
            get {
                return ResourceManager.GetString("ErrorResultBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定した操作を実行するアクセス権がありません。.
        /// </summary>
        public static string ErrorResultForbidden {
            get {
                return ResourceManager.GetString("ErrorResultForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーで予期しないエラーが発生しました。.
        /// </summary>
        public static string ErrorResultInternalServerError {
            get {
                return ResourceManager.GetString("ErrorResultInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証スキームが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidAuthorizationScheme {
            get {
                return ResourceManager.GetString("ErrorResultInvalidAuthorizationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証トークンが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidAuthorizationToken {
            get {
                return ResourceManager.GetString("ErrorResultInvalidAuthorizationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クライアントの認証に失敗しました。.
        /// </summary>
        public static string ErrorResultInvalidClient {
            get {
                return ResourceManager.GetString("ErrorResultInvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認可コードが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidCode {
            get {
                return ResourceManager.GetString("ErrorResultInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限種別が正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidGrantType {
            get {
                return ResourceManager.GetString("ErrorResultInvalidGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リフレッシュトークンが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidRefreshToken {
            get {
                return ResourceManager.GetString("ErrorResultInvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコープが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidScope {
            get {
                return ResourceManager.GetString("ErrorResultInvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証ヘッダーを指定してください。.
        /// </summary>
        public static string ErrorResultNoAuthorizationHeader {
            get {
                return ResourceManager.GetString("ErrorResultNoAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定したリソースは存在しません。.
        /// </summary>
        public static string ErrorResultNotFound {
            get {
                return ResourceManager.GetString("ErrorResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証情報が正しくありません。.
        /// </summary>
        public static string ErrorResultUnauthorized {
            get {
                return ResourceManager.GetString("ErrorResultUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力エラーが発生しました。エラーメッセージを確認してください。.
        /// </summary>
        public static string ErrorResultValidationError {
            get {
                return ResourceManager.GetString("ErrorResultValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos;に対する値&apos;{0}&apos;は正しくありません。.
        /// </summary>
        public static string ModelBindingAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ModelBindingAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に対するパラメーターまたはプロパティが指定されていません。.
        /// </summary>
        public static string ModelBindingMissingBindRequiredValueAccessor {
            get {
                return ResourceManager.GetString("ModelBindingMissingBindRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値を入力してください。.
        /// </summary>
        public static string ModelBindingMissingKeyOrValueAccessor {
            get {
                return ResourceManager.GetString("ModelBindingMissingKeyOrValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字以外の本文を入力してください。.
        /// </summary>
        public static string ModelBindingMissingRequestBodyRequiredValueAccessor {
            get {
                return ResourceManager.GetString("ModelBindingMissingRequestBodyRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値&apos;{0}&apos;は正しくありません。.
        /// </summary>
        public static string ModelBindingNonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ModelBindingNonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定された値が無効です。.
        /// </summary>
        public static string ModelBindingNonPropertyUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ModelBindingNonPropertyUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィールドは数字を指定してください。.
        /// </summary>
        public static string ModelBindingNonPropertyValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ModelBindingNonPropertyValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に対する値は正しくありません。.
        /// </summary>
        public static string ModelBindingUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ModelBindingUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値&apos;{0}&apos;は正しくありません。.
        /// </summary>
        public static string ModelBindingValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ModelBindingValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィールド&apos;{0}&apos;は数字を指定してください。.
        /// </summary>
        public static string ModelBindingValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ModelBindingValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値&apos;{0}&apos;は正しくありません。.
        /// </summary>
        public static string ModelBindingValueMustNotBeNullAccessor {
            get {
                return ResourceManager.GetString("ModelBindingValueMustNotBeNullAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に指定した&apos;{1}&apos;に対応するデータが存在しません。.
        /// </summary>
        public static string ValidationDataNotFound {
            get {
                return ResourceManager.GetString("ValidationDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値はすでに登録されています。.
        /// </summary>
        public static string ValidationDuplicated {
            get {
                return ResourceManager.GetString("ValidationDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;が登録されているため削除することはできません。.
        /// </summary>
        public static string ValidationHasChildren {
            get {
                return ResourceManager.GetString("ValidationHasChildren", resourceCulture);
            }
        }
    }
}
